### ISSUE TITLE
Unable to add this as blue-prints for --skip-client and --skip-server

### ISSUE THREAD

**Issue by jgdvarun60** [sonalake/generator-jhipster-multitenancy#136]

**Comment by jduggan83** [comment]
Hi, the server element is fundamental to this blueprint. Im surprised howver that the skip client option does not work for you

**Comment by jgdvarun60** [comment]
As its not supported with latest version of jhipster (I think 6.8) 
I tried with lower version of jhipster v6.3.1, this error is reporduceble with any jdl, just giving test jdl for reference

```
application {
  config {
    baseName test,
    applicationType monolith,
    packageName com.test
    authenticationType session,
    prodDatabaseType mysql,
    devDatabaseType mysql,
    cacheProvider ehcache,
    buildTool maven,
    clientFramework react,
    useSass false,
    testFrameworks []
  }
  entities *
}

entity Aa
entity Ba
entity Ca
entity Da
entity Ea
entity Fa
entity Ga
entity Ha
entity Pa

relationship OneToMany {
    Pa{aabc} to Aa{pabc} 
    Ba{pabc} to Pa{babc}
}

relationship ManyToOne {
    Pa{cabc} to Ca 
    Da{pabc} to Pa
}

relationship OneToOne {
    Pa{eabc} to Ea{pabc} 
    Fa{pabc} to Pa{fabc}
}

relationship ManyToMany {
    Pa{gabc} to Ga{pabc} 
    Ha{pabc} to Pa{habc}
}

filter Pa
dto * with mapstruct
service * with serviceImpl
```


**generate server code** 
`jhipster import-jdl test.jh --skip-client `
...

**add blueprint**
`jhipster --with-entity --blueprints multitenancy --skip-client`
... 
_I think first time it installs the blueprint only, so I ran the same command again_ 

`jhipster --with-entity --blueprints multitenancy --skip-client`

`
? What is the alias given to tenants in your application? Organization
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: This module currently only supports Angular and React

    at Environment.error (test/server/node_modules/yeoman-environment/lib/environment.js:176:40)
    at module.exports.error (test/server/node_modules/generator-jhipster/generators/generator-base.js:1464:18)
    at module.exports.validateCompatibility (test/server/node_modules/generator-jhipster-multitenancy/generators/common/index.js:128:26)
    at Object.<anonymous> (test/server/node_modules/yeoman-generator/lib/index.js:424:27)
    at test/server/node_modules/run-async/index.js:47:25
    at new Promise (<anonymous>)
    at test/server/node_modules/run-async/index.js:24:19
    at test/server/node_modules/yeoman-generator/lib/index.js:425:13
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (test/server/node_modules/yeoman-generator/lib/index.js:433:22)
    at processImmediate (internal/timers.js:439:21)`


I am trying to separate client and server as per 
`https://www.jhipster.tech/separating-front-end-and-api/ `
So I should be able to generate client and server separately...

**Comment by jduggan83** [comment]
Thanks very much for this detail. I will investigate
