### ISSUE TITLE
Error during jhipster-multitenancy execution 

### ISSUE THREAD

**Issue by tcbuzor** [sonalake/generator-jhipster-multitenancy#36]
Hi, 
I updated generator-jhipster-multitenancy and ran  yo jhipster-multitenancy on a new jhipster generated project and still got the exception below:
cmd: yarn global upgrade generator-jhipster-multitenancy && yo jhipster-multitenancy
jhipster version: 5.1.0

Error:
Welcome to the JHipster Multitenancy Generator v0.9.6

? What is the alias given tenants in your application? Tenant
events.js:183
throw er; // Unhandled 'error' event
^

ReferenceError: /usr/local/lib/node_modules/generator-jhipster-multitenancy/generators/app/templates/src/main/java/package/domain/_User.java:169
167| private String id;<% } %>
168|

169| <%_ let columnMax = 50;
170| if (enableSocialSignIn) {
171| columnMax = 100;
172| } _%>

enableSocialSignIn is not defined
at eval (eval at compile (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/ejs/lib/ejs.js:618:12), :155:5)
at returnedFn (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/ejs/lib/ejs.js:653:17)
at Object.exports.render (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/ejs/lib/ejs.js:416:37)
at process (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
at applyProcessingFunc (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:63:16)
at files.forEach.file (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:50:10)
at Array.forEach ()
at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:49:9)
at EditionInterface.module.exports [as copyTpl] (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)

**Comment by alexander-ozkan** [comment]
Hi @tcbuzor, it would appear that the multitenancy generator being run hasn't been updated (outputting v0.9.6 instead of v1.0.0).

Give this a try and let me know how it goes: `npm i generator-jhipster-multitenancy`

**Comment by tcbuzor** [comment]
It worked after trying with npm i generator-jhipster-multitenancy
Thanks
