### ISSUE TITLE
Cannot init multitenancy v1.0.5 with jhipster v5.8.1

### ISSUE THREAD

**Issue by clakech** [sonalake/generator-jhipster-multitenancy#53]
With jhipster 5.8.1 I face this error with  jhipster-multitenancy 1.0.5

$yo jhipster-multitenancy

                               Multitenancy Module

Welcome to the JHipster Multitenancy Generator v1.0.5

? What is the alias given tenants in your application? Company
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'serverLiquibase' of undefined
    at child.addChangelogToLiquibase (/Users/cyrillakech/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/generators/generator-base.js:529:24)
    at child.generateServerCode (/Users/cyrillakech/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster-multitenancy/generators/app/index.js:162:18)
    at Object.<anonymous> (/Users/cyrillakech/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:418:27)
    at /Users/cyrillakech/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster-multitenancy/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/cyrillakech/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster-multitenancy/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/cyrillakech/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:419:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/cyrillakech/.nvm/versions/node/v10.15.0/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:427:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by hnitzsche** [comment]
It doesn't throw this error if you install jhipster-multitenancy in your project as dependency instead of globally.

**Comment by clakech** [comment]
thanks for answer, let's try that

**Comment by oosodrac** [comment]
i try but don´t work

**Comment by jduggan83** [comment]
Hi, thanks for reporting, we will get a fix out as soon as possible

**Comment by sch0lar** [comment]
I started to explore this generator and hit this same issue. Thanks for looking into it. Would love to try it out once fixed.

**Comment by jduggan83** [comment]
@clakech I cant recreate this issue. Can you please share your yo-rc.json file? Thanks
