### ISSUE TITLE
problem installing yo jhipster-multitenancy

### ISSUE THREAD

**Issue by abrorabdukadirov** [sonalake/generator-jhipster-multitenancy#57]
npm version: 6.10.1
 
yo jhipster-multitenancy

events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'endsWith' of undefined
    at child.getAngularAppName (C:\Users\User\AppData\Roaming\npm\node_modules\generator-jhipster-multitenancy\node_modules\generator-jhipster\generators\generator-base.js:1647:56)
    at child.readConfig (C:\Users\User\AppData\Roaming\npm\node_modules\generator-jhipster-multitenancy\generators\app\index.js:26:40)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\generator-jhipster-multitenancy\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:418:27)
    at C:\Users\User\AppData\Roaming\npm\node_modules\generator-jhipster-multitenancy\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\User\AppData\Roaming\npm\node_modules\generator-jhipster-multitenancy\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\User\AppData\Roaming\npm\node_modules\generator-jhipster-multitenancy\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:419:13)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\User\AppData\Roaming\npm\node_modules\generator-jhipster-multitenancy\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:427:22)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)

**Comment by ciarant** [comment]
Hi there. By any chance are you running 'yo jhipster-multitenancy' in an empty directory?

**Comment by kvmarkovich** [comment]
> Hi there. By any chance are you running 'yo jhipster-multitenancy' in an empty directory?

I have the same issue.
```
bash-3.2$ npm -v
6.9.0
```
I'm running it in an empty directory.

`bash-3.2$ ls
bash-3.2$ yo jhipster-multitenancy
events.js:180
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'endsWith' of undefined
    at child.getAngularAppName (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/generators/generator-base.js:1647:56)
    at child.readConfig (/usr/local/lib/node_modules/generator-jhipster-multitenancy/generators/app/index.js:26:40)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:418:27)
    at /usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:419:13
    at processImmediate (internal/timers.js:439:21)
Emitted 'error' event at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:427:22)
    at processImmediate (internal/timers.js:439:21)
bash-3.2$ `

**Comment by ciarant** [comment]
You need to run it in the root directory of an existing JHipster project.

**Comment by kvmarkovich** [comment]
The problem is solved. Thanks!

```
bash-3.2$ yo jhipster-multitenancy
Error jhipster-multitenancy 

ERROR! 
Your generated project used a JHipster version (6.1.2) that is currently not supported.

```
