### ISSUE TITLE
Error when generating project

### ISSUE THREAD

**Issue by amatosg** [sonalake/generator-jhipster-multitenancy#94]
I unable to generate a project using JHipster 6.4.1

After answering all the questions, I get this error:

```
I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.



The entity Company is being created.

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: The generator-jhipster-multitenancy blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-multitenancy.
    at Environment.error (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:176:40)
    at module.exports.error (/usr/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/generators/generator-base.js:1448:18)
    at shelljs.exec (/usr/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/generators/generator-base-private.js:839:22)
    at /usr/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/node_modules/shelljs/src/exec.js:127:9
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
Emitted 'error' event at:
    at Environment.error (/usr/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:178:15)
    at module.exports.error (/usr/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/generators/generator-base.js:1448:18)
    [... lines matching original stack trace ...]
    at Pipe._handle.close (net.js:606:12)
```

**Comment by Kelvijn** [comment]
I have the same error. Even when downgrading Jhipster generator to 6.2.0, which is the latest version you claim to support.

**Comment by jduggan83** [comment]
Hi @Kelvijn Can you provide a bit more information on your issue. Are you using a jdl? or can you send on the yo-rc config, or the error you are seeing?

**Comment by jduggan83** [comment]
Closing issue as no more information provided
