### ISSUE TITLE
Strange Behavior Creating a MultiTenancy Project ManyToMany Issue

### ISSUE THREAD

**Issue by hepaestus** [sonalake/generator-jhipster-multitenancy#95]
Trying to create a project using multi tenancy. See the Project Setup Information Below.
See the errors below when I try to run ./mvnw command.

Thanks,
P.
----

pete@Medussa:~/git/offerLetterJhipster/test16 (master) $ jhipster info
```
INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

offer-letter@0.0.1-SNAPSHOT /home/pete/git/offerLetterJhipster/test16
├── generator-jhipster@6.3.1 
├─┬ generator-jhipster-angular-material-integration@1.0.17
│ └── generator-jhipster@6.3.1  deduped
└─┬ generator-jhipster-multitenancy@2.0.1
  └── generator-jhipster@6.2.0 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.odysseysystems"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "monolith",
    "baseName": "OfferLetter",
    "packageName": "com.odysseysystems",
    "packageFolder": "com/odysseysystems",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-angular-material-integration",
        "version": "1.0.17"
      },
      {
        "name": "generator-jhipster-multitenancy",
        "version": "2.0.1"
      }
    ],
    "enableTranslation": false,
    "blueprints": [
      {
        "name": "generator-jhipster-multitenancy",
        "version": "2.0.1"
      }
    ]
  },
  "generator-jhipster-multitenancy": {
    "tenantChangelogDate": "20191001193117",
    "jhipsterVersion": "6.3.1",
    "applicationType": "monolith",
    "baseName": "OfferLetter",
    "packageName": "com.odysseysystems",
    "packageFolder": "com/odysseysystems",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "tenantName": "Company",
    "tenantAwareEntities": [
      "Candidate",
      "Offer",
      "Approval",
      "OfferSignature",
      "CompiledOffer",
      "OfferContent",
      "DefaultOfferContent",
      "Attachments",
      "Paragraph",
      "ParagraphPlacement",
      "SpecialConditions",
      "EmailSystemConfig",
      "EmailConfiguration",
      "Recipient",
      "CompanyContact",
      "OfficeLocation"
    ],
    "embeddableLaunchScript": false
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Company {
  companyName String,
  companyDescription String
}
entity OfficeLocation {
  name String,
  description String,
  address1 String,
  address2 String,
  city String,
  state String,
  postalCode String,
  country String,
  priority Integer,
  type String
}
entity Candidate {
  salutation String,
  firstName String,
  lastName String,
  email String,
  address1 String,
  address2 String,
  city String,
  state String
}
entity Offer {
  positionID String,
  offerName String,
  uniqueLinkID String,
  startingDate LocalDate,
  expirationDate LocalDate,
  description String
}
entity Approval {
  ready Boolean,
  compliance Boolean,
  finalreview Boolean,
  rejected Boolean,
  reason TextBlob,
  requestor String
}
entity OfferSignature {
  dateSigned LocalDate,
  fullName String,
  signature AnyBlob,
  message TextBlob,
  accepted Boolean
}
entity CompiledOffer {
  finishedOffer AnyBlob
}
entity OfferContent {
  offerDate LocalDate,
  startingDate LocalDate,
  dutyLocation String,
  programOffice String,
  includeProgramOffice Boolean,
  weeklyHours String,
  wages Long,
  flsaCategory String,
  minClearance String,
  includeMinClearance Boolean,
  positionTitle String,
  reportsTo String,
  description String
}
entity DefaultOfferContent {
  subject String,
  companyName String,
  footer TextBlob,
  header TextBlob,
  logo ImageBlob,
  description String
}
entity Attachments {
  description String,
  attachment AnyBlob
}
entity Paragraph {
  paragraphText TextBlob,
  paragraphName String
}
entity ParagraphPlacement {
  order Long
}
entity SpecialConditions {
  conditionDescription String,
  condition TextBlob
}
entity EmailSystemConfig {
  secretKey AnyBlob,
  serviceAccountID String,
  serviceAccountUser String
}
entity EmailConfiguration {
  type String,
  content TextBlob,
  subject String
}
entity Recipient {
  type String,
  address String
}
entity CompanyContact {
  firstName String,
  lastName String,
  department String,
  phoneNumber String,
  email String,
  office String,
  title String,
  type String
}
relationship OneToOne {
  Company{emailSystemConfig} to EmailSystemConfig{company},
  Company{defaultOfferContent} to DefaultOfferContent{company},
  Offer{approval} to Approval{offer},
  Offer{offerSignature} to OfferSignature{offer},
  Offer{compiledOffer} to CompiledOffer{offer}
}
relationship OneToMany {
  Company{officeLocation} to OfficeLocation{company},
  Company{candidate} to Candidate{company},
  OfferContent{offer} to Offer{offerContent},
  Candidate{offer} to Offer{candidate},
  ParagraphPlacement{paragraph} to Paragraph{paragraphPlacement},
  Company{companyContact} to CompanyContact{company}
}
relationship ManyToMany {
  Company{emailConfiguration} to EmailConfiguration{company},
  OfferContent{paragraph} to Paragraph{offerContent},
  OfferContent{attachments} to Attachments{offerContent},
  OfferContent{specialConditions} to SpecialConditions{offerContent},
  EmailConfiguration{recipient} to Recipient{emailConfiguration}
}


</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.20.1

node: v10.16.0

npm: 6.11.3

yeoman: 3.1.0

yarn: 1.15.2

Docker version 19.03.2, build 6a30dfca03

docker-compose version 1.21.0, build unknown

INFO! Congratulations, JHipster execution is complete!
```

========================
pete@Medussa:~/git/offerLetterJhipster/test16 (master) $ ./mvnw

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< com.odysseysystems:offer-letter >-------------------
[INFO] Building Offer Letter 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:2.1.8.RELEASE:run (default-cli) > test-compile @ offer-letter >>>
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (default-resources) @ offer-letter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 65 resources
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ offer-letter ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 65 resources
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ offer-letter ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-dependencyConvergence) @ offer-letter ---
[WARNING] 
Dependency convergence error for org.apiguardian:apiguardian-api:1.0.0 paths to dependency are:
+-com.odysseysystems:offer-letter:0.0.1-SNAPSHOT
  +-org.junit.jupiter:junit-jupiter-engine:5.3.2
    +-org.apiguardian:apiguardian-api:1.0.0
and
+-com.odysseysystems:offer-letter:0.0.1-SNAPSHOT
  +-org.junit.jupiter:junit-jupiter-engine:5.3.2
    +-org.junit.platform:junit-platform-engine:1.3.2
      +-org.apiguardian:apiguardian-api:1.0.0
and
+-com.odysseysystems:offer-letter:0.0.1-SNAPSHOT
  +-org.junit.jupiter:junit-jupiter-engine:5.3.2
    +-org.junit.platform:junit-platform-engine:1.3.2
      +-org.junit.platform:junit-platform-commons:1.3.2
        +-org.apiguardian:apiguardian-api:1.0.0
and
+-com.odysseysystems:offer-letter:0.0.1-SNAPSHOT
  +-org.junit.jupiter:junit-jupiter-engine:5.3.2
    +-org.junit.jupiter:junit-jupiter-api:5.3.2
      +-org.apiguardian:apiguardian-api:1.0.0
and
+-com.odysseysystems:offer-letter:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.0
    +-org.zalando:problem-violations:0.25.0
      +-org.apiguardian:apiguardian-api:1.0.0
and
+-com.odysseysystems:offer-letter:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.0
    +-org.zalando:problem-spring-common:0.25.0
      +-org.apiguardian:apiguardian-api:1.1.0
and
+-com.odysseysystems:offer-letter:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.0
    +-org.apiguardian:apiguardian-api:1.1.0
and
+-com.odysseysystems:offer-letter:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.0
    +-org.zalando:problem:0.23.0
      +-org.apiguardian:apiguardian-api:1.0.0
and
+-com.odysseysystems:offer-letter:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.0
    +-org.zalando:jackson-datatype-problem:0.23.0
      +-org.apiguardian:apiguardian-api:1.0.0
and
+-com.odysseysystems:offer-letter:0.0.1-SNAPSHOT
  +-org.zalando:problem-spring-web:0.25.0
    +-org.zalando:faux-pas:0.8.0
      +-org.apiguardian:apiguardian-api:1.0.0

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability. See above detailed error message.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.4:prepare-agent (pre-unit-tests) @ offer-letter ---
[INFO] argLine set to -javaagent:/home/pete/.m2/repository/org/jacoco/org.jacoco.agent/0.8.4/org.jacoco.agent-0.8.4-runtime.jar=destfile=/home/pete/git/offerLetterJhipster/test16/target/jacoco/test/test.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
[INFO] 
[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ offer-letter ---
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ offer-letter ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 146 source files to /home/pete/git/offerLetterJhipster/test16/target/classes
[INFO] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/aop/company/CandidateAspect.java: Some input files use unchecked or unsafe operations.
[INFO] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/aop/company/CandidateAspect.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/domain/Company.java:[205,27] cannot find symbol
  symbol:   method getCompanies()
  location: variable emailConfiguration of type com.odysseysystems.domain.EmailConfiguration
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/domain/Company.java:[211,27] cannot find symbol
  symbol:   method getCompanies()
  location: variable emailConfiguration of type com.odysseysystems.domain.EmailConfiguration
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/domain/User.java:[154,16] cannot find symbol
  symbol:   variable company
  location: class com.odysseysystems.domain.User
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/domain/User.java:[158,13] cannot find symbol
  symbol: variable company
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/service/CompanyService.java:[50,33] cannot find symbol
  symbol:   method findAllWithEagerRelationships()
  location: variable companyRepository of type com.odysseysystems.repository.CompanyRepository
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/service/CompanyService.java:[59,33] cannot find symbol
  symbol:   method findAllWithEagerRelationships(org.springframework.data.domain.Pageable)
  location: variable companyRepository of type com.odysseysystems.repository.CompanyRepository
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/service/CompanyService.java:[72,33] cannot find symbol
  symbol:   method findOneWithEagerRelationships(java.lang.Long)
  location: variable companyRepository of type com.odysseysystems.repository.CompanyRepository
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/web/rest/CompanyResource.java:[120,39] cannot find symbol
  symbol:   method getUsers()
  location: variable company of type com.odysseysystems.domain.Company
[INFO] 8 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.665 s
[INFO] Finished at: 2019-10-21T12:25:29-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project offer-letter: Compilation failure: Compilation failure: 
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/domain/Company.java:[205,27] cannot find symbol
[ERROR]   symbol:   method getCompanies()
[ERROR]   location: variable emailConfiguration of type com.odysseysystems.domain.EmailConfiguration
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/domain/Company.java:[211,27] cannot find symbol
[ERROR]   symbol:   method getCompanies()
[ERROR]   location: variable emailConfiguration of type com.odysseysystems.domain.EmailConfiguration
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/domain/User.java:[154,16] cannot find symbol
[ERROR]   symbol:   variable company
[ERROR]   location: class com.odysseysystems.domain.User
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/domain/User.java:[158,13] cannot find symbol
[ERROR]   symbol: variable company
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/service/CompanyService.java:[50,33] cannot find symbol
[ERROR]   symbol:   method findAllWithEagerRelationships()
[ERROR]   location: variable companyRepository of type com.odysseysystems.repository.CompanyRepository
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/service/CompanyService.java:[59,33] cannot find symbol
[ERROR]   symbol:   method findAllWithEagerRelationships(org.springframework.data.domain.Pageable)
[ERROR]   location: variable companyRepository of type com.odysseysystems.repository.CompanyRepository
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/service/CompanyService.java:[72,33] cannot find symbol
[ERROR]   symbol:   method findOneWithEagerRelationships(java.lang.Long)
[ERROR]   location: variable companyRepository of type com.odysseysystems.repository.CompanyRepository
[ERROR] /home/pete/git/offerLetterJhipster/test16/src/main/java/com/odysseysystems/web/rest/CompanyResource.java:[120,39] cannot find symbol
[ERROR]   symbol:   method getUsers()
[ERROR]   location: variable company of type com.odysseysystems.domain.Company
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

pete@Medussa:~/git/offerLetterJhipster/test16 (master) $ cat jhipster-jdl.jh 
```
entity Company{
    companyName String
    companyDescription String
}

entity OfficeLocation {
    name String
    description String
    address1 String
    address2 String
    city String
    state String
    postalCode String
    country String	
    priority Integer
    type String
}

entity Candidate {
	salutation String
    firstName String
    lastName String
    email String
    address1 String
    address2 String
    city String
    state String
}

entity Offer {
    positionID String
    offerName String
    uniqueLinkID String
    startingDate LocalDate
    expirationDate LocalDate
    description String
}

entity Approval {
    ready Boolean
    compliance Boolean
    finalreview Boolean
    rejected Boolean
    reason TextBlob
    requestor String
}

entity OfferSignature{
    dateSigned LocalDate
    fullName String
    signature AnyBlob
    message TextBlob
    accepted Boolean
}

entity CompiledOffer{
    finishedOffer AnyBlob
}

entity OfferContent{
    offerDate LocalDate
    startingDate LocalDate
    dutyLocation String
    programOffice String
    includeProgramOffice Boolean
    weeklyHours String
    wages Long
    flsaCategory String
    minClearance String
    includeMinClearance Boolean
    positionTitle String
    reportsTo String
    description String
}

entity DefaultOfferContent{
    subject String
    companyName String
    footer TextBlob
    header TextBlob
    logo ImageBlob
    description String
}

entity Attachments{
    description String
    attachment AnyBlob
}

entity Paragraph{
    paragraphText TextBlob
    paragraphName String
}

entity ParagraphPlacement{
    order Long
}

entity SpecialConditions{
    conditionDescription String
    condition TextBlob
}

entity EmailSystemConfig{
    secretKey AnyBlob
    serviceAccountID String
    serviceAccountUser String
}

entity EmailConfiguration{
    type String
    content TextBlob
    subject String
}

entity Recipient{
    type String
    address String
}

entity CompanyContact{
    firstName String
    lastName String
    department String
    phoneNumber String
    email String
    office String
    title String
    type String
}

relationship OneToOne{
    Offer to Approval
    Offer to OfferSignature
    Offer to CompiledOffer
    Company to EmailSystemConfig
    Company to DefaultOfferContent    
}

relationship OneToMany{
    Company to Candidate
    Company to OfficeLocation
    Company to CompanyContact    
}

relationship ManyToOne{
    Offer to OfferContent
    Offer to Candidate
    Paragraph to ParagraphPlacement
}

relationship ManyToMany{
	Company to EmailConfiguration
    EmailConfiguration to Recipient
    OfferContent to Paragraph
    OfferContent to Attachments
    OfferContent to SpecialConditions
}
pete@Medussa:~/git/offerLetterJhipster/test16 (master) $ cat jhipster-jdl.jh 
entity Company{
    companyName String
    companyDescription String
}

entity OfficeLocation {
    name String
    description String
    address1 String
    address2 String
    city String
    state String
    postalCode String
    country String	
    priority Integer
    type String
}

entity Candidate {
	salutation String
    firstName String
    lastName String
    email String
    address1 String
    address2 String
    city String
    state String
}

entity Offer {
    positionID String
    offerName String
    uniqueLinkID String
    startingDate LocalDate
    expirationDate LocalDate
    description String
}

entity Approval {
    ready Boolean
    compliance Boolean
    finalreview Boolean
    rejected Boolean
    reason TextBlob
    requestor String
}

entity OfferSignature{
    dateSigned LocalDate
    fullName String
    signature AnyBlob
    message TextBlob
    accepted Boolean
}

entity CompiledOffer{
    finishedOffer AnyBlob
}

entity OfferContent{
    offerDate LocalDate
    startingDate LocalDate
    dutyLocation String
    programOffice String
    includeProgramOffice Boolean
    weeklyHours String
    wages Long
    flsaCategory String
    minClearance String
    includeMinClearance Boolean
    positionTitle String
    reportsTo String
    description String
}

entity DefaultOfferContent{
    subject String
    companyName String
    footer TextBlob
    header TextBlob
    logo ImageBlob
    description String
}

entity Attachments{
    description String
    attachment AnyBlob
}

entity Paragraph{
    paragraphText TextBlob
    paragraphName String
}

entity ParagraphPlacement{
    order Long
}

entity SpecialConditions{
    conditionDescription String
    condition TextBlob
}

entity EmailSystemConfig{
    secretKey AnyBlob
    serviceAccountID String
    serviceAccountUser String
}

entity EmailConfiguration{
    type String
    content TextBlob
    subject String
}

entity Recipient{
    type String
    address String
}

entity CompanyContact{
    firstName String
    lastName String
    department String
    phoneNumber String
    email String
    office String
    title String
    type String
}

relationship OneToOne{
    Offer to Approval
    Offer to OfferSignature
    Offer to CompiledOffer
    Company to EmailSystemConfig
    Company to DefaultOfferContent    
}

relationship OneToMany{
    Company to Candidate
    Company to OfficeLocation
    Company to CompanyContact    
}

relationship ManyToOne{
    Offer to OfferContent
    Offer to Candidate
    Paragraph to ParagraphPlacement
}

relationship ManyToMany{
    Company to EmailConfiguration
    EmailConfiguration to Recipient
    OfferContent to Paragraph
    OfferContent to Attachments
    OfferContent to SpecialConditions
}
```

**Comment by jduggan83** [comment]
Hi Peter, thanks for all the info. Just taking a very quick look at it, I can see that you have Company defined in your jdl and have specified company to be your tenant. The multitenancy blueprint automatically creates the tenant entity so you might have an issue here defining the entity in your jdl as well. I'll run the blueprint using your config to verify.

**Comment by hepaestus** [comment]
Yes, I do have the tenant object inside the JDL Import file. What is the correct syntax for using the COMPANY as the tenant while creating the necessary relationships. IE the ManyToMany fro Company to EmailConfiguration?  Thanks!

**Comment by hepaestus** [comment]
Any help with that syntax?

**Comment by jduggan83** [comment]
Hi, at the moment we don't support specifying relationships for the tenant on immediate creation of the app via a jdl, so there is no correct syntax for this. We will have a look into this. What I think you should do for now is create your app without the tenant in your jdl then use the entity generator to make each of your entities tenant aware and any other relationships you need.

**Comment by hepaestus** [comment]
I will give that a try. Thanks.

**Comment by hepaestus** [comment]
SO.... I updated my JDL to remove the Company Object and all relationships to company.  Then I ran 
this script below:
```
 sudo npm install  generator-jhipster-multitenancy
 sudo npm update generator-jhipster-multitenancy
 sudo npm link generator-jhipster-multitenancy
 npm install
 npm update
 jhipster --with-entities --blueprints multitenancy
 jhipster import-jdl jhipster-jdl_MT.jh --blueprints multitenancy
 jhipster entity company
```
My JDL Import file has not Company Entity or any Company Relationships.
I am getting the following error:

```
Entity Recipient found. Adding relationship
Saving Recipient tenantAware
Entity CompanyContact found. Adding relationship
Saving CompanyContact tenantAware
     info Using blueprint generator-jhipster-multitenancy for entity-server subgenerator
     info Using blueprint generator-jhipster-multitenancy for entity-client subgenerator
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: The generator-jhipster-multitenancy blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-multitenancy.
    at Environment.error (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:176:40)
    at module.exports.error (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/generators/generator-base.js:1448:18)
    at shelljs.exec (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/generators/generator-base-private.js:839:22)
    at /usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/node_modules/shelljs/src/exec.js:127:9
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)
Emitted 'error' event at:
    at Environment.error (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:178:15)
    at module.exports.error (/usr/local/lib/node_modules/generator-jhipster-multitenancy/node_modules/generator-jhipster/generators/generator-base.js:1448:18)
    [... lines matching original stack trace ...]
    at Pipe._handle.close (net.js:606:12)
jhipster entity company
cp ../pom.xml .; cp ../application-dev.yml src/main/resources/config/.; cp ../application.yml src/main/resources/config/.
```
Thanks,
Pete.

**Comment by jduggan83** [comment]
Thanks for the detail Peter. Running through these steps now and will give you a response soon

**Comment by hepaestus** [comment]
Let me know if you need any more info! :)

**Comment by CharlotteFawsitt** [comment]
The fix for this issue is now in the latest release
